version: '3'
services:
  app:
    image: node:18
    container_name: caplist-serverless
    volumes:
      - ./src:/projects
      - ./src/data/buckets:/data/buckets/caplist
    working_dir: /projects/caplist
    ports:
      - "760:3000"
      - "745:4569"
    networks:
      - verisure
    command: sh -c "if [ ! -d /projects/node_modules ]; then npm install; fi && npm run dev"
      
networks:
  verisure:
    external: true