AWSTemplateFormatVersion: "2010-09-09"
Description: ZipCode Enabled infra

Parameters:
  ProjectPrefix:
    Type: String
    Default: vs
    Description: Prefix used to naming all resources

  ProjectName:
    Type: String
    Default: zipcode-enabled
    Description: Project name. Default is <zipcode-enabled>

  Country:
    Type: String
    Default: all
    AllowedValues:
      - all
      - it
      - nl
    Description: Country used for the deploy. Available values are [all|it|nl]. Use <all> to use a generic country

  Environment:
    Type: String
    AllowedValues:
      - stage
      - production
    Description: Environment of the current project. Available values are [stage|production]

Resources:
  QueueEntrypoint:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName:
        Fn::Join:
          - "-"
          - - Ref: ProjectName
            - Ref: Environment
            - Ref: Country
            - "entrypoint"

  QueueStatsIndex:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName:
        Fn::Join:
          - "-"
          - - Ref: ProjectName
            - Ref: Environment
            - Ref: Country
            - "zipcode-index"

Outputs:
  QueueEntrypointUrl:
    Value: !GetAtt QueueEntrypoint.QueueUrl
  QueueEntrypointArn:
    Value: !GetAtt QueueEntrypoint.Arn

  QueueStatsIndexUrl:
    Value: !GetAtt QueueStatsIndex.QueueUrl
  QueueStatsIndexArn:
    Value: !GetAtt QueueStatsIndex.Arn