service: caplist

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  memorySize: 128
  timeout: 10
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}
    MYSQL_DSN: ${file(./serverless.${self:provider.stage}.yml):mysql-dsn}
    CAP_BUCKET: ${file(./serverless.${self:provider.stage}.yml):cap-bucket}
    DISTRIBUTION_ID: ${file(./serverless.${self:provider.stage}.yml):cf-distribution-id}

package:
  exclude:
    - data/**
    - docker/**
    - package.json
    - package-lock.json
    - README.md

plugins:
  - serverless-offline
  - serverless-s3-local
  - serverless-dotenv-plugin

functions:
  entrypoint:
    name: ${self:service}-entrypoint
    handler: handler.entrypoint
    timeout: 30

custom:
  serverless-offline:
    host: 0.0.0.0
    useChildProcesses: true
  s3:
    host: localhost
    directory: /data/buckets/${self:service}
    address: 0.0.0.0

